openapi: 3.0.0
info:
  title: Plataforma de Streaming de Música API
  version: 1.0.0
  description: Uma API para gerenciar músicas, playlists, artistas e usuários.

paths:
  /usuarios:
    get:
      summary: Lista todos os usuários
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example: { "usuarios": [...] }

    post:
      summary: Cria um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            example: { "nome_usuario": "novousuario", "email": "novousuario@email.com" }
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              example: { "mensagem": "Usuário criado com sucesso", "usuario": {...} }

  /usuarios/{usuarioId}:
    get:
      summary: Obtém detalhes de um usuário específico
      parameters:
        - name: usuarioId
          in: path
          required: true
          description: ID do usuário
          schema:
            type: integer
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example: { "usuario": {...} }

    put:
      summary: Atualiza um usuário existente
      parameters:
        - name: usuarioId
          in: path
          required: true
          description: ID do usuário
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            example: { "nome_usuario": "novonome" }
      responses:
        '200':
          description: Usuário atualizado com sucesso
          content:
            application/json:
              example: { "mensagem": "Usuário atualizado com sucesso", "usuario": {...} }

    delete:
      summary: Exclui um usuário
      parameters:
        - name: usuarioId
          in: path
          required: true
          description: ID do usuário
          schema:
            type: integer
      responses:
        '204':
          description: Usuário excluído com sucesso

  /usuarios/{usuarioId}/playlists:
    get:
      summary: Lista todas as playlists de um usuário
      parameters:
        - name: usuarioId
          in: path
          required: true
          description: ID do usuário
          schema:
            type: integer
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example: { "playlists": [...] }

    post:
      summary: Cria uma nova playlist para um usuário
      parameters:
        - name: usuarioId
          in: path
          required: true
          description: ID do usuário
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            example: { "titulo": "Nova Playlist" }
      responses:
        '201':
          description: Playlist criada com sucesso
          content:
            application/json:
              example: { "mensagem": "Playlist criada com sucesso", "playlist": {...} }

  /playlists/{playlistId}:
    get:
      summary: Obter detalhes de uma playlist específica
      parameters:
        - name: playlistId
          in: path
          required: true
          description: ID da playlist
          schema:
            type: integer
      responses:
        '200':
          description: Retorna os detalhes da playlist
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID da playlist
                  nome:
                    type: string
                    description: Nome da playlist
                  usuarioId:
                    type: integer
                    description: ID do usuário associado à playlist

    put:
      summary: Atualizar uma playlist existente
      parameters:
        - name: playlistId
          in: path
          required: true
          description: ID da playlist
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Novo nome da playlist
                usuarioId:
                  type: integer
                  description: Novo ID do usuário associado à playlist
      responses:
        '200':
          description: Playlist atualizada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID da playlist
                  mensagem:
                    type: string
                    description: Mensagem de sucesso

    delete:
      summary: Excluir uma playlist
      parameters:
        - name: playlistId
          in: path
          required: true
          description: ID da playlist a ser excluída
          schema:
            type: integer
      responses:
        '204':
          description: Playlist excluída com sucesso
 
  /musicas:
    get:
      summary: Obter todas as músicas
      responses:
        '200':
          description: Retorna todas as músicas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: ID da música
                    titulo:
                      type: string
                      description: Título da música
                    artistaId:
                      type: integer
                      description: ID do artista associado à música

    post:
      summary: Adicionar uma nova música
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  description: Título da música
                artistaId:
                  type: integer
                  description: ID do artista associado à música
      responses:
        '201':
          description: Música adicionada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID da nova música
                  mensagem:
                    type: string
                    description: Mensagem de sucesso

  /musicas/{musicaId}:
    get:
      summary: Obter detalhes de uma música específica
      parameters:
        - name: musicaId
          in: path
          required: true
          description: ID da música
          schema:
            type: integer
      responses:
        '200':
          description: Retorna os detalhes da música
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID da música
                  titulo:
                    type: string
                    description: Título da música
                  artistaId:
                    type: integer
                    description: ID do artista associado à música

    put:
      summary: Atualizar uma música existente
      parameters:
        - name: musicaId
          in: path
          required: true
          description: ID da música
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  description: Novo título da música
                artistaId:
                  type: integer
                  description: Novo ID do artista associado à música
      responses:
        '200':
          description: Música atualizada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID da música
                  mensagem:
                    type: string
                    description: Mensagem de sucesso

    delete:
      summary: Excluir uma música
      parameters:
        - name: musicaId
          in: path
          required: true
          description: ID da música a ser excluída
          schema:
            type: integer
      responses:
        '204':
          description: Música excluída com sucesso        
 
  /artistas:
    get:
      summary: Obter todos os artistas
      responses:
        '200':
          description: Retorna todos os artistas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: ID do artista
                    nome:
                      type: string
                      description: Nome do artista

    post:
      summary: Adicionar um novo artista
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome do artista
      responses:
        '201':
          description: Artista adicionado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID do novo artista
                  mensagem:
                    type: string
                    description: Mensagem de sucesso

  /artistas/{artistaId}:
    get:
      summary: Obter detalhes de um artista específico
      parameters:
        - name: artistaId
          in: path
          required: true
          description: ID do artista
          schema:
            type: integer
      responses:
        '200':
          description: Retorna os detalhes do artista
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID do artista
                  nome:
                    type: string
                    description: Nome do artista

    put:
      summary: Atualizar um artista existente
      parameters:
        - name: artistaId
          in: path
          required: true
          description: ID do artista
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Novo nome do artista
      responses:
        '200':
          description: Artista atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID do artista
                  mensagem:
                    type: string
                    description: Mensagem de sucesso

    delete:
      summary: Excluir um artista
      parameters:
        - name: artistaId
          in: path
          required: true
          description: ID do artista a ser excluído
          schema:
            type: integer
      responses:
        '204':
          description: Artista excluído com sucesso